# Generated by Django 3.2.5 on 2021-09-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_apply_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='apply',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website/Portfolio link'),
        ),
    ]
