# Generated by Django 3.2.5 on 2021-10-13 14:51

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20211013_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(upload_to=job.models.upload_cv),
        ),
    ]
